add_lunch_combo aokp_mako-userdebug
add_lunch_combo aokp_manta-userdebug
add_lunch_combo aokp_grouper-userdebug
add_lunch_combo aokp_tilapia-userdebug
add_lunch_combo aokp_amami-userdebug
add_lunch_combo aokp_m7spr-userdebug
add_lunch_combo aokp_m7vzw-userdebug
add_lunch_combo aokp_m8-userdebug
add_lunch_combo aokp_mango-userdebug
add_lunch_combo aokp_mint-userdebug
add_lunch_combo aokp_moto_msm8960dt-userdebug
add_lunch_combo aokp_mione_plus-userdebug

